[package]
name = "harmonia"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29"
eframe = "0.29"
egui_node_graph2 = "0.7"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
